### ISSUE TITLE
Can't compile on Cordova 6.1

### ISSUE THREAD

**Issue by anteburazer** [videostream/cordova-chromecast#60]
Hi

I'm not able to build the application on Cordova 6.1 with Android SDK 23. I'm using Ionic 1 framework to build a hybrid mobile app.
Here's the error from console:

`MY_PROJECT\platforms\android\build\intermediates\manifests\full\debug\AndroidManifest.xml:45:28-65 : AAPT: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').`

I tried to cheat so I hardcoded Google Play Services version in '_MY_PROJECT/platforms/android/android.json_' file.
This solves the issue but then I ran into another one:

`MY_PROJECT/platforms\android\src\acidhax\cordova\chromecast\Chromecast.java:12: error: package com.google.android.gms.cast does not exist
import com.google.android.gms.cast.CastMediaControlIntent;`

I checked the file mentioned above and '_com.google.android.gms.cast.CastMediaControlIntent_' is imported so I'm not sure what's the problem.

I also tried to implement solution #59 but it didn't help.

Does anybody know where is the problem?
Thanks

**Comment by Bek81** [comment]
Hi anteburazer,

after several searches, I found this possible workaround:

open your _build.gradle_ file and modify 
`dependencies {
        classpath 'com.android.tools.build:gradle:...'
    }`

to:
`classpath 'com.android.tools.build:gradle:1.5.0'`.

Try this.

After this change I encountered another issue.

**Comment by Bek81** [comment]
Hi,

Try this workaround:
open build.gradle and modify the code:

`android {
...
}`

adding:
`dependencies {
        compile fileTree(include: ['*.jar'], dir: 'libs')
        compile 'com.google.android.gms:play-services:8.4.0'
}`.

Anyway, after this change I encountered another issue.

**Comment by Bek81** [comment]
Hi,

here my new issue stacktrace:
> ...
:prepareComGoogleAndroidGmsPlayServicesWallet840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesWearable840Library UP-TO-DATE
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:compileDebugJavaWithJavac/path/to/project/platforms/android/src/acidhax/cordova/chromecast/Chromecast.java:777: error: cannot find symbol
                    webView.evaluateJavascript(javascript, null);
                           ^
  symbol:   method evaluateJavascript(String,<null>)
  location: variable webView of type CordovaWebView
/path/to/project/platforms/android/src/acidhax/cordova/chromecast/Chromecast.java:772: error: cannot find symbol
        webView.post(new Runnable() {
               ^
  symbol:   method post(<anonymous Runnable>)
  location: variable webView of type CordovaWebView
Note: /path/to/project/platforms/android/src/acidhax/cordova/chromecast/ChromecastSession.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.863 secs
Error: Error code 1 for command: /path/to/project/platforms/android/gradlew with args: cdvBuildDebug,-b,/path/to/project/platforms/android/build.gradle,-PcdvBuildArch=x86,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true

Can anyone help me?

**Comment by jmterminator** [comment]
So I got this working. First I had to use the changes from the pull request: https://github.com/videostream/cordova-chromecast/pull/59

Then I had to open up the Android SDK Manager and install Google Play services, Google Repository, and Android Support Library.

After all of this, I was able to build an Ionic 2 app successfully.

**Comment by Danyzzz** [comment]
I have the same problem as @Bek81... @jmterminator can you explain your solution please?
Thanks!
